#!/usr/bin/env python3
""" Implements poly_integral function
"""
import numpy as np


def poly_integral(poly):
    """ Calculates the integral of a given polynomial
    """
    p = np.array(poly)

    # Create new powers
    powers = np.arange(1, p.size + 1)

    # Divide p by new powers
    p = p / powers

    # Move every p to the next position(increasing power value)
    p = np.array([0]) + p

    return  p
