#!/usr/bin/env python3
""" Implements poly_integral function
"""


def poly_integral(poly):
    """ Calculates the integral of a given polynomial
    """
    return [0] + list(map(poly, lambda x, i: x / (i + 1)))
